In [117]:
import pandas as pd
import numpy as np
import seaborn as sns
import nltk
from nltk.corpus import wordnet
url=""
base_dataset=pd.read_csv(r'C:\Users\Aritra\Desktop\Athena\FSM PRO answers.csv')

In [118]:
base_dataset

,Name,Mobile Number,Address Flat Name,Address Flat Number,Address Door Number,Address Street Name,Address Location Name,Address City Name,Pincode,Building Type,...,q22,Average waiting time in community toilet,GPS Location of household,Year of OSS Construction,q28_donotknow,Have you desludged your on site sanitation system before,Desludging frequency of on site sanitation system,Property can be accessed by road of width greater than 3m,Distance of access by road with mechanized tank,Access to On site Sanitation on reaching premise
0,Test,6.000000e+00,NaN,NaN,675,NaN,NaN,NaN,NaN,Thatched,...,NaN,26.0,"24.0819311, 89.6298448, 77.5999984741211, 0",2013.0,0,Yes,5.0,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
1,Md. Mujam Molla,1.724508e+09,NaN,8,2,NaN,Bangabaria,Bera,6680,Tin-shed,...,NaN,NaN,"24.0667158, 89.6150114, 3099.9990234375, 0",NaN,0,NaN,20.0,NaN,NaN,NaN
2,Md. Bablu Mondol,1.763385e+09,NaN,NaN,40,NaN,Bangabari,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0756503, 89.6211919, 2299.9990234375, 0",2011.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
3,Md. Hafijur Rahman,1.771496e+09,NaN,8,95,Bangabaria,Bangabaria,Bera,6680,Tin-shed,...,NaN,NaN,"24.0652307, 89.6156001, 3099.9990234375, 0",2018.0,0,No,NaN,Yes,Within 100feet,Can be accessed with a lot of effort upon reac...
4,Md. Shohidul Islam,1.722389e+09,NaN,8,135,Bangabaria,Bangabaria,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0756503, 89.6211919, 2299.9990234375, 0",2009.0,0,No,NaN,Yes,Within 300feet,Can be easily accessible upon reaching the pr...
5,Md. Abdus Samad Moholdar,1.732961e+09,NaN,8,175,Bangabaria,Bangabaria,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0767674, 89.6220747, 2099.9990234375, 0",2009.0,0,No,NaN,No,Cannot be accessible from road and can be desl...,Can be easily accessible upon reaching the pr...
6,Md.Amirul islam,1.719462e+09,3,NaN,1,Bonogram Dokkin,Bonogeram Dokkin,BERA,6680,Pucca,...,NaN,NaN,"24.0823206, 89.6135397, 2599.9990234375, 0",NaN,1,Yes,6.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
7,Md. Lal mia,1.734708e+09,O3,NaN,35,NaN,Bonogeram Dokkin,Bera,6680,Semi-pucca,...,0.0,0.0,"24.0823206, 89.6135397, 2599.9990234375, 0",2018.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
8,Md .Rotan Fokir,1.734507e+09,3,NaN,70,NaN,BONOGERAM north-west,Bera,6680,Tin-shed,...,0.0,0.0,"24.0823206, 89.6135397, 2599.9990234375, 0",NaN,1,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
9,Md.nurul islam,1.751606e+09,NaN,10,39,D0tt0kandi,Dottokandi,Bera,668o,Semi-pucca,...,NaN,NaN,"24.07997, 89.6102336, 23, 8.800000190734863",2010.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
10,Md. Kurban molla,1.777571e+09,6,NaN,O2,NaN,Palkhand,Bera,6680,Tin-shed,...,NaN,NaN,"24.0661102, 89.6479495, 12, -50.90000152587...",2014.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
11,Md. Barek Pramanik,1.752167e+09,NaN,10,75,Dottokandi,Dottokandi,Bera,668o,Tin-shed,...,NaN,NaN,"24.0806253, 89.6100763, 17, -41.40000152587...",2019.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
12,Alok kumar pal,1.719202e+09,NaN,9,64,NaN,Dakshin karmokar para,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0806708, 89.6251699, 17.5, -47.799999237...",2014.0,0,No,NaN,Yes,Within 200feet,Can be accessed with minimal effort upon reach...
13,Md. Jumat Ali Fakir,1.745619e+09,NaN,10,15o,Dottokandi,Dottikando,Bera,668o,Semi-pucca,...,NaN,NaN,"24.0789567, 89.6096098, 13, -32.70000076293945",2012.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
14,Md. Awyal,1.760246e+09,6,NaN,30,NaN,Paikhand,Bera,6680,Tin-shed,...,NaN,NaN,"24.0665246, 89.6487704, 15.5, -56.200000762...",2011.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
15,Hazi Hobibor Rahman,1.711393e+09,9,NaN,33,NaN,Bera Bazer,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0816618, 89.624689, 11.5, -20.2000007629...",1983.0,0,Yes,30.0,Yes,Within 200feet,Can be accessed with minimal effort upon reach...
16,Md. Almamoun,1.648171e+09,O3,NaN,105,NaN,Bonogeram Dokkin,Bera,6680,Tin-shed,...,0.0,0.0,"24.0823206, 89.6135397, 2599.9990234375, 0",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
17,Md. Kamrul lslam,1.795681e+09,6,NaN,61,NaN,Paikhand,Bera,6680,Tin-shed,...,NaN,NaN,"24.0672179, 89.6496223, 12.5, -8",NaN,0,NaN,1.0,NaN,NaN,NaN
18,Md. Altaf Hossain,1.725443e+09,9,NaN,91,NaN,Dakshin Kormoker para,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0810635, 89.6226362, 12, -34.70000076293945",2000.0,0,Yes,1500.0,No,Cannot be accessible from road and can be desl...,Can be accessed with minimal effort upon reach...
19,Md. Islam Fakir,1.721338e+09,NaN,10,190,Dottokandi,Dottikandi,Bera,6680,Tin-shed,...,NaN,NaN,"24.0788774, 89.6095419, 11, 1.600000023841858",2019.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
20,MD. Abdul alim,1.794228e+09,6,NaN,93,NaN,Paikhand,Bera,6680,Tin-shed,...,NaN,NaN,"24.0671101, 89.6502212, 10.5, -38.400001525...",NaN,0,NaN,1.0,NaN,NaN,NaN
21,Md. Motin,1.913825e+09,3,NaN,140,NaN,Bonogeram Dokkin,Bera,6680,Tin-shed,...,0.0,0.0,"24.0823206, 89.6135397, 2599.9990234375, 0",2015.0,0,No,NaN,No,Within 100feet,Can be easily accessible upon reaching the pr...
22,Md. Bablu Kha,1.714232e+09,NaN,10,228,Dottokandi,Dottokandi,Bera,668o,Tin-shed,...,NaN,NaN,"24.0781911, 89.6085311, 98.4000015258789, 0",2018.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
23,Mst. Sufia khtun,1.754255e+09,6,NaN,123,NaN,Paikhand,Bera,6680,Tin-shed,...,NaN,NaN,"24.0650577, 89.6500231, 24.5, 50.7999992370...",2016.0,0,No,NaN,Yes,Within 200feet,Can be accessed with minimal effort upon reach...
24,Mostak ahmmed Nannu,1.713745e+09,1,NaN,2,NaN,Brishalikha,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0971824, 89.6123624, 4800, 0",2010.0,0,Yes,1.0,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
25,Md raza molla,1.770098e+09,NaN,NaN,42,Brishalikha poscimpara,Brishalikha,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0971824, 89.6123624, 4800, 0",2019.0,0,Yes,1.0,No,Within 100feet,Can be easily accessible upon reaching the pr...
26,Md jahangir hossen,1.723135e+09,NaN,NaN,81,Brishalikha poshimpara,Brishalikha,Bera,6680,Tin-shed,...,NaN,NaN,"24.0971824, 89.6123624, 4800, 0",2009.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
27,Md.Uzzal Hossain,1.937487e+09,NaN,2,1,NaN,Bonogram North,Bera,6680,Tin-shed,...,NaN,NaN,"24.0840962, 89.6180454, 15, -55.09999847412...",2018.0,0,No,NaN,Yes,Within 300feet,Can be easily accessible upon reaching the pr...
28,Md. Mizanur Rahman Nanna,1.779652e+09,NaN,2,149,NaN,Bonogram North,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0848011, 89.6178367, 23, -22.10000038146...",2010.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
29,Md. Alom Molla,1.738894e+09,NaN,NaN,36,NaN,Bonogram North,Bera,6680,Tin-shed,...,NaN,NaN,"24.0847077, 89.6167947, 12.5, -46.200000762...",2012.0,0,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Md. Monirujjaman baccu,1.722928e+09,NaN,8,974.1,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0703745, 89.6097092, 18, -66.80000305175781",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
347,Md.mintu pramanik,1.925119e+09,NaN,8,990,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0711818, 89.6107937, 12, -86",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
348,Md. Mujibul haqe altu,1.780753e+09,NaN,8,1012,NaN,Shanila,Bera pourashava,6680,Pucca,...,NaN,NaN,"24.0712952, 89.6108152, 38.5, -66.900001525...",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with a lot of effort upon reac...
349,Md. Nobi pramanik,1.722376e+09,NaN,8,1051,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0724583, 89.6105562, 96, -48.40000152587...",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
350,Md. Yousuf ali khan,1.918762e+09,NaN,8,1034,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0726291, 89.610249, 96, -58.29999923706055",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
351,Sree shudir chandra,1.920047e+09,NaN,8,1146,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0725836, 89.6084389, 49.5, -36.5",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
352,Sree norash,1.925450e+09,NaN,8,1379,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0729011, 89.6083777, 45.5, -37.200000762...",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
353,Md. Sidul islam,1.764769e+09,NaN,8,11409,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0728167, 89.6083145, 49.5, -70.5",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
354,Abu bakkar,1.739747e+09,NaN,8,1510,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0701066, 89.6086033, 25.45599937438965, ...",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
355,md. Ludfor molla,1.778856e+09,NaN,8,1484.524,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0702086, 89.6078423, 23.5, -63.799999237...",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
356,Md. Montu shakh,1.752169e+09,NaN,8,1466,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0696718, 89.6081018, 13.02400016784668, ...",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
357,Md. Ujjol hossdain,1.753476e+09,NaN,8,1526,NaN,Shanila,Bera p0urashava,6680,Tin-shed,...,NaN,NaN,"24.0693514, 89.6083972, 20.5, -31.600000381...",NaN,1,Yes,365.0,Yes,Cannot be accessible from road and can be desl...,Can be easily accessible upon reaching the pr...
358,Md. Ruhul amin mastar,1.912684e+09,NaN,8,881,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0682518, 89.6092767, 96, -33",NaN,1,Yes,800.0,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
359,Md. Amod ali,1.737298e+09,NaN,8,858,NaN,Shanila,Bera pourashava,6680,Pucca,...,NaN,NaN,"24.0675287, 89.6100686, 96, -43.70000076293945",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
360,Md. Shajahan ali,1.731286e+09,NaN,8,1238,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0758571, 89.6076046, 15, -39.79999923706055",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
361,Md. Mojnu pramanik,1.774726e+09,NaN,8,1632,NaN,Shanila,Bera pourashav,6680,Tin-shed,...,NaN,NaN,"24.0756548, 89.6075077, 22.5, -71.900001525...",NaN,1,Yes,300.0,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
362,Md. Amirul islam,1.793367e+09,NaN,8,1246,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,2.0,"24.0756746, 89.6078818, 37, -26.79999923706...",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
363,Md abu said,1.712518e+09,NaN,8,1311,NaN,Shanila,Bera pourashava,6680,Semi-pucca,...,7.0,NaN,"24.0755159, 89.607805, 44, -8.699999809265137",NaN,1,Yes,400.0,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
364,Md. Abdur rahaman,1.738662e+09,NaN,8,1266,NaN,Shanila,Berapourashava,6680,Tin-shed,...,NaN,NaN,"24.0754124, 89.6086877, 44.5, -34.299999237...",2015.0,0,Yes,576.0,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
365,Md. Ashraf ali,1.716835e+09,NaN,8,1088,NaN,Shanila,Berapourashava,6680,Tin-shed,...,NaN,NaN,"24.074283, 89.6098532, 96, 13.399999618530273",2017.0,0,Yes,365.0,Yes,Within 200feet,Can be easily accessible upon reaching the pr...
366,Md. Abdus samad,1.727034e+09,NaN,8,1617,NaN,Shanila,Bera pourashava,6680,Pucca,...,NaN,NaN,"24.0743359, 89.6074327, 18, -52",NaN,1,No,NaN,Yes,Within 100feet,Can be accessed with minimal effort upon reach...
367,Md. Cascu,1.752401e+09,NaN,8,1604,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0733001, 89.6075608, 24, -47.5",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
368,Md. Jakaria hossain,1.928931e+09,NaN,8,1737,NaN,Shanila,Bera pourashava,6680,Tin-shed,...,NaN,NaN,"24.0705393, 89.6077538, 15, -44.09999847412...",NaN,1,No,NaN,Yes,Within 100feet,Can be easily accessible upon reaching the pr...
369,MD. Soriful,1.756826e+09,5,NaN,1392,NaN,Buro payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0730775, 89.6329615, 2299.9990234375, 0",2019.0,0,No,NaN,No,Cannot be accessible from road and can be desl...,Can be accessed with minimal effort upon reach...
370,MD. Moktar,1.795900e+09,5,NaN,1408,NaN,Buro payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0728601, 89.6325645, 2289, 0",2016.0,0,No,NaN,No,Cannot be accessible from road and can be desl...,Can be accessed with minimal effort upon reach...
371,MD. Majem,1.757753e+09,5,NaN,1425,NaN,Soto payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0790354, 89.6379625, 3400, 0",NaN,0,NaN,1.0,NaN,NaN,NaN
372,MD. Monirul,1.748201e+09,5,NaN,1441,NaN,Buro payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0790389, 89.6394333, 3000, 0",NaN,0,NaN,1.0,NaN,NaN,NaN
373,MD. Rubel,1.776698e+09,5,NaN,1457,NaN,Buro payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0790354, 89.6379625, 3400, 0",2019.0,0,No,NaN,Yes,Within 200feet,Can be easily accessible upon reaching the pr...
374,MD. Rejaul,1.729133e+09,5,NaN,1478,NaN,Buro payna,Bera,6680,Tin-shed,...,NaN,NaN,"24.0790389, 89.6394333, 3000, 0",NaN,0,NaN,1.0,NaN,NaN,NaN
375,MD. Momin,1.748477e+09,6,NaN,1020,NaN,Varadiya,Bera,6680,Semi-pucca,...,NaN,NaN,"24.0727058, 89.6329615, 2299.9990234375, 0",2014.0,0,No,NaN,No,Cannot be accessible from road and can be desl...,Can be accessed with minimal effort upon reach...

In [119]:
base_dataset.columns

Index(['Name', 'Mobile Number', 'Address Flat Name', 'Address Flat Number',
       'Address Door Number', 'Address Street Name', 'Address Location Name',
       'Address City Name', 'Pincode', 'Building Type', 'Building Types',
       'Carpet Area', 'Level of education', 'Own House',
       'Type of items owned at home', 'Type of house', 'Have a toilet',
       'If toilet not present do you access community toilet',
       'Distance at which community toilet is situated',
       'Time to reach community toilet', 'Total population in house',
       'Total male population in house', 'Total female population in house',
       'Do all members use either household or community toilet', 'q21', 'q22',
       'Average waiting time in community toilet', 'GPS Location of household',
       'Year of OSS Construction', 'q28_donotknow',
       'Have you desludged your on site sanitation system before',
       'Desludging frequency of on site sanitation system',
       'Property can be accessed by road of width greater than 3m',
       'Distance of access by road with mechanized tank',
       'Access to On site Sanitation on reaching premise'],
      dtype='object')

In [120]:
cont=base_dataset.describe().columns

In [121]:
cont

Index(['Mobile Number', 'Building Types', 'Carpet Area',
       'Distance at which community toilet is situated',
       'Time to reach community toilet', 'Total population in house',
       'Total male population in house', 'Total female population in house',
       'q21', 'q22', 'Average waiting time in community toilet',
       'Year of OSS Construction', 'q28_donotknow',
       'Desludging frequency of on site sanitation system'],
      dtype='object')

In [122]:
cat=[i for i in base_dataset.columns if i not in base_dataset.describe().columns]

In [123]:
cat

['Name',
 'Address Flat Name',
 'Address Flat Number',
 'Address Door Number',
 'Address Street Name',
 'Address Location Name',
 'Address City Name',
 'Pincode',
 'Building Type',
 'Level of education',
 'Own House',
 'Type of items owned at home',
 'Type of house',
 'Have a toilet',
 'If toilet not present do you access community toilet',
 'Do all members use either household or community toilet',
 'GPS Location of household',
 'Have you desludged your on site sanitation system before',
 'Property can be accessed by road of width greater than 3m',
 'Distance of access by road with mechanized tank',
 'Access to On site Sanitation on reaching premise']

In [170]:
columns_list=base_dataset.columns
functions={'frequency':'value_counts()','unique':'nunique()','min':'min()','smallest':'min()','minimum':'min()','least':'min()','lowest':'min()','max':'max()','maximum':'max()','greatest':'max()','highest':'max()','largest':'max()','mean':'mean()','average':'mean()','median':'median()','sum':'sum()','total':'sum()','aggregate':'sum()','summation':'sum()','intersection':'intersection(x)','summary':'describe()','summarize':'describe()','describe':'describe()','variance':'var()','count':'count()','many':'count()','much':'count()','standard':'std()','deviation':'std()','root':'sqrt','sqrt':'sqrt','multiplication':'multi','rug':''}
condition={'greater than':'>','more than':'>','lesser than ':'<','lower than':'<','equal to':'='}
list_1=['and','or']

In [226]:
ques=""

In [134]:
def func7():
    if ' intersection ' in ques:
        column1=[]
        for i in columns_list:
            if i in ques:
                column1.append(i)
        if len(column1)==2:
            a1=set(base_dataset[column1[0]])
            b1=set(base_dataset[column1[1]])
            print(a1&b1)
        elif len(column1)==3:
            a1=set(base_dataset[column1[0]])
            b1=set(base_dataset[column1[1]])
            c1=set(base_dataset[column1[2]])
            print(a1&b1&c1)
        elif len(column1)==4:
            a1=set(base_dataset[column1[0]])
            b1=set(base_dataset[column1[1]])
            c1=set(base_dataset[column1[2]])
            d1=set(base_dataset[column1[3]])
            print(a1&b1&c1&d1)
    
    elif ' union ' in ques:
        column1=[]
        for i in columns_list:
            if i in ques:
                column1.append(i)
        if len(column1)==2:
            a1=list(base_dataset[column1[0]])
            b1=list(base_dataset[column1[1]])
            print(set(a1+b1))
        elif len(column1)==3:
            a1=list(base_dataset[column1[0]])
            b1=list(base_dataset[column1[1]])
            c1=list(base_dataset[column1[2]])
            print(set(a1+b1+c1))
        elif len(column1)==4:
            a1=list(base_dataset[column1[0]])
            b1=list(base_dataset[column1[1]])
            c1=list(base_dataset[column1[2]])
            d1=list(base_dataset[column1[3]])
            print(set(a1+b1+c1+d1))

In [198]:
def func1():
    if ' correlation ' in ques:
        print(base_dataset.corr()) 
    else:
        function1=None
        for i in columns_list:
            if i in ques:
                columns=i
        for i in ques.split():
            if i in functions:
                functions1=i
        x=functions[functions1]
        if x == 'sqrt':
            print(np.sqrt(base_dataset[columns]))
        else:
            print(eval("base_dataset[columns]"+"."+x))

In [126]:
def func2():
    column1=[]
    if ' greater than ' in ques:
        for i in columns_list:
            if i in ques:
                column1.append(i)
        print(column1)
        aggregated_columns=input()
        column2=[]
        function1=None
        column2=[i for i in column1 if i not in aggregated_columns]
        for k in ques.split():
            if k in functions:
                function1=k
        x=functions[function1]
        for c in ques.split():
            if c.isdigit():
                num=c
        print(eval("base_dataset[base_dataset[aggregated_columns]>"+ num +"][column2]."+x))

    column1=[]
    if 'less than' in ques:
        for i in columns_list:
            if i in ques:
                column1.append(i)
        print(column1)
        column2=[]
        function1=None
        aggregated_columns=input()
        column2=[i for i in column1 if i not in aggregated_columns]
        for k in ques.split():
            if k in functions:
                function1=k
        x=functions[function1]
        for c in ques.split():
            if c.isdigit():
                num=c
        print(eval("base_dataset[base_dataset[aggregated_columns]<"+ num +"][column2]."+x))


    column1=[]
    if ' equal to ' in ques:
        for i in columns_list:
            if i in ques:
                column1.append(i)
        print(column1)
        column2=[]
        function1=None
        aggregated_columns=input()
        column2=[i for i in column1 if i not in aggregated_columns]
        for k in ques.split():
            if k in functions:
                function1=k
        x=functions[function1]
        for c in ques.split():
            if c.isdigit():
                num=c
        print(eval("base_dataset[base_dataset[aggregated_columns]="+ num +"][column2]."+x))

In [127]:
def func3():
    if ' rug plot ' in ques:
        for i in columns_list:
            if i in ques:
                columns=i
        sns.rugplot(base_dataset[columns])
        
    if ' kde plot ' in ques:
        column1=[]
        for i in columns_list:
            if i in ques:
                column1.append(i)
        if len(column1)==1:
            sns.kdeplot(base_dataset[column1[0]])
        elif len(column1)==2:
            sns.kdeplot(base_dataset[column1[0]],base_dataset[column1[1]],shade=True,cbar=True)
    
    if ' joint plot ' in ques:
        column1=[]
        for i in columns_list:
            if i in ques:
                column1.append(i)
        if 'linear regression' in ques:
            sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='reg')
        elif 'kernel density' in ques:
            sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='kde')
        elif 'hexagon' in ques:
            sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='hex')
        else:
            sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]])
        
    if ' dist plot ' in ques:
        for i in columns_list:
            if i in ques:
                columns=i
        base_dataset_copy=base_dataset
        base_dataset_copy[columns].fillna(0,inplace=True)
        sns.distplot(base_dataset_copy[columns])
    
    if ' pair plot ' in ques:
        column1=[]
        for i in columns_list:
            if i in ques:
                column1.append(i)
        column1_copy=[]
        for i in column1:
            column1_copy.append(base_dataset[i])
        column1_copy=pd.DataFrame(column1_copy).T
        if 'kernel density' in ques:
            sns.pairplot(column1_copy,diag_kind='kde')
        elif 'linear regression' in ques:
            sns.pairplot(column1_copy,kind='reg')
        else:
            sns.pairplot(column1_copy)

In [128]:
def func4():
    operator = 'and'
    cols2=[]
    num1=[]
    func1=[]
    for i in columns_list:
        if i in ques:
            cols2.append(i)
    for i in ques.split():
        if i in functions.keys():
            func1.append(i)
        elif i.isdigit():
            num1.append(i)
    column_1=cols2[1]
    column_2=cols2[2]
    column_3=cols2[0]
    function_key_1=func1[1]
    function_key_2=func1[2]
    function_key_3=func1[0]
    function_1=functions[function_key_1]
    function_2=functions[function_key_2]
    function_3=functions[function_key_3]
    number1=num1[0]
    number2=num1[1]
    w=[]
    ques_comb1=[]
    for i in ques.split('and'):
        ques_comb1.append(i)
    for i in ques_comb1:
        if ' greater than ' in i:
            w.append('>')
        elif ' more than ' in i:
            w.append('>')
        elif ' less than ' in i:
            w.append('<')
        elif ' lower than ' in i:
            w.append('<')
    if operator=='and' :
        if eval(("base_dataset[column_1]."+function_1+w[0]+number1) and ("base_dataset[column_2]." +function_2+w[1] + number2)):
            print(eval("base_dataset[column_3]."+function_3))

In [130]:
def func5():
    operator = 'or'
    cols3=[]
    num2=[]
    func2=[]
    for i in columns_list:
        if i in ques:
            cols3.append(i)
    for i in ques.split():
        if i in functions.keys():
            func2.append(i)
        elif i.isdigit():
            num2.append(i)
    column_1_1=cols3[1]
    column_2_2=cols3[2]
    column_3_3=cols3[0]
    function_key_1=func2[1]
    function_key_2=func2[2]
    function_key_3=func2[0]
    function_1_1=functions[function_key_1]
    function_2_2=functions[function_key_2]
    function_3_3=functions[function_key_3]
    number1=num2[0]
    number2=num2[1]
    w=[]
    ques_comb1=[]
    for i in ques.split('and'):
        ques_comb1.append(i)
    for i in ques_comb1:
        if ' greater than ' in i:
            w.append('>')
        elif ' more than ' in i:
            w.append('>')
        elif ' less than ' in i:
            w.append('<')
        elif ' lower than ' in i:
            w.append('<')
    if operator=='or' :
        if eval(("base_dataset[column_1_1]."+function_1_1+w[0]+number1) or ("base_dataset[column_2_2]." +function_2_2+w[1] + number2)):
            print(eval("base_dataset[column_3_3]."+function_3_3))

In [222]:
def func6():
    ques_split =[]
    result_split=[]
    function11=None
    for i in ques.split(' and '):
        ques_split.append(i)
    for k in ques_split:
        for i in columns_list:
            if i in k:
                column11=i
        for j in functions:
            if j in k:
                function11=j
        x2=functions[function11]
        result = eval("base_dataset[column11]"+"."+x2)
        result_split.append(result)
    for i in result_split:
        print(i)

In [186]:
ques="Can you please show me the median of Mobile Number if mean of Carpet Area is greater than 10 or count of Total population in house is greater than 20"

In [225]:
ques = "Show the median of Mobile Number"

In [190]:
ques="Show the pair plot of Total male population in house and Total population in house"

In [194]:
ques="Show the union of Total male population in house and Total female population in house"

In [84]:
column1=[]
for i in columns_list:
    if i in ques:
        column1.append(i)
        
column1

['Total population in house', 'Total male population in house']

In [211]:
base_dataset['Carpet Area'].mean()

44.293510638297874

In [67]:
base_dataset[base_dataset['Mobile Number']<100]['Carpet Area'].std()

1106.041289162992

In [226]:
if (' intersection ' in ques) or (' union ' in ques):
    func7()
elif ' plot ' in ques:
    func3()
elif (' if 'in ques) and (' and ' in ques):
    func4()
elif (' if ' in ques) and (' or ' in ques):
    func5()
elif ' if 'in ques:
    func2()
elif ' and ' in ques:
    func6()
else:
    func1()

1747106886.0

In [57]:
mydic={}

for i in functions.keys():
    synonyms=[]
    for syn in wordnet.synsets(i):
        for l in syn.lemmas():
            synonyms.append(l.name())
    mydic[i]=synonyms

# END OF CODE

ques="Can you please show me the median of Mobile Number if mean of Mobile Number is greater than 10 or count of Total population in house is less than 20"

ques_split

ques_split =[]
result_split=[]
function11=None
for i in ques.split(' & '):
    ques_split.append(i)
for qz in ques_split: 
    for i in columns_list:
        if i in qz:
            column11=i
for j in ques.split():
    if j in functions:
        function11=j
    x2=functions[function11]
    result = eval("base_dataset[column11]"+"."+x2)
    result_split.append(result)
for i in result_split:
    print(i)

ques="Can you please show me the median of Mobile Number if mean of Carpet Area is greater than 10 and count of Total population in house is greater than 20"

cols2

eval(("base_dataset[column_2]." +function_2+w[1] + number2))

operator = 'and'
cols2=[]
num1=[]
func1=[]
for i in columns_list:
    if i in ques:
        cols2.append(i)
for i in ques.split():
    if i in functions.keys():
        func1.append(i)
    elif i.isdigit():
        num1.append(i)
column_1=cols2[1]
column_2=cols2[2]
column_3=cols2[0]
function_key_1=func1[1]
function_key_2=func1[2]
function_key_3=func1[0]
function_1=functions[function_key_1]
function_2=functions[function_key_2]
function_3=functions[function_key_3]
number1=num1[0]
number2=num1[1]
w=[]
ques_comb1=[]
for i in ques.split('and'):
    ques_comb1.append(i)
for i in ques_comb1:
    if ' greater than ' in i:
        w.append('>')
    elif ' more than ' in i:
        w.append('>')
    elif ' less than ' in i:
        w.append('<')
    elif ' lower than ' in i:
        w.append('<')
if operator=='and' :
    if eval(("base_dataset[column_1]."+function_1+w[0]+number1) and ("base_dataset[column_2]." +function_2+w[1] + number2)):
        print(eval("base_dataset[column_3]."+function_3))

ques = "Show the median of Mobile Number and mean of Carpet Area"

ques_split

for k in ques_split:
     for j in k:
        if j in functions:
            function11=j
            
function11

ques_split =[]
result_split=[]
function11=None
for i in ques.split(' and '):
    ques_split.append(i)
for k in ques_split:
    for i in columns_list:
        if i in k:
            column11=i
    for j in functions:
        if j in k:
            function11=j
    x2=functions[function11]
    result = eval("base_dataset[column11]"+"."+x2)
    result_split.append(result)
for i in result_split:
    print(i)

base_dataset['fare'].median()

base_dataset['fare'].mean()

ques = "Show the mean of fare and median of fare"

ques_split

x2

base_dataset[column11].mean()

o=ques_split[0]
for j in o.split():
    if j in columns_list:
        column11=j
    elif j in functions:
        function11=j
x2=functions[function11]
if x2 == 'sqrt':
    print(np.sqrt(base_dataset[column11]))
else:
    print(eval("base_dataset[column11]"+"."+x2))

for i in (ques_comb):
    for k in i:
        if k in columns_list:
            columns_7=k
        elif k in functions:
            functions11=k
    x1=functions[functions11]
    if x2 == 'sqrt':
        result = (np.sqrt(base_dataset[columns_7]))
        result_comb.append(result)
    else:
        result = eval("base_dataset[columns_7]"+"."+x)
        result_comb.append(result)

columns_7

ques_comb=[]
if ' and ' in ques:
    result_comb=[]
    for i in ques.split('and'):
        ques_comb.append(i)
        for j in ques_comb:
            for k in j.split():
                function1=None
                for h in k.split():
                    if h in columns_list:
                        columns_7=h
                    elif h in functions:
                        function11=h
                x2=functions[function11]
                if x2 == 'sqrt':
                    result = (np.sqrt(base_dataset[columns_7]))
                    result_comb.append(result)
                else:
                    result = eval("base_dataset[columns_7]"+"."+x)
                    result_comb.append(result)

In [429]:
result_comb

[512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292,
 512.3292]

In [406]:
func6()

512.3292
512.3292

In [204]:
ques="Show the median of age if mean of age is greater than 10 and count of fare is less than 10"

In [200]:
w[1]

'>'

In [209]:
for i in ques_comb1:
    if ' less than ' in i:
        w.append('<')

In [210]:
w

['>', '>', '<', '<']

In [211]:
ques_comb1

['Show the median of age if mean of age is greater than 10 ',
 ' count of fare is less than 10']

In [213]:
w

['>', '<']

In [212]:
w=[]
ques_comb1=[]
for i in ques.split('and'):
    ques_comb1.append(i)
for i in ques_comb1:

In [ ]:
def and_function(columns1, column2 , operator, aggregator,number1,number2):

In [ ]:
else :
    if base_dataset[column1].mean()<number1 or base_dataset[column2].count()<number2:
         print(base_dataset['age'].median())

In [41]:
ques="How many present in adult_male"

In [40]:
columns_list

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [42]:
function1=None
for i in ques.split():
    if i in columns_list:
        columns=i
    elif i in functions:
        function1=i
x=functions[function1]
if x == 'sqrt':
    print(np.sqrt(base_dataset[columns]))
else:
    print(eval("base_dataset[columns]"+"."+x))

891

In [128]:
b=list(functions.values())

In [129]:
a=list(mydic.values())

In [ ]:
for i in a:

a = x.split() (" ").join(a[2:4])

Yeh correlation wala func kaise chalau???

baki sare jitne hai that are of the form df[column].func
corr wala sirf df.corr hai and if i try to put the "172" wala code in a else -if then the whole code doesnt run
any suggestions?
call pe bATA

In [ ]:
x1 = list(mydic.values())
x1[0][0]

In [ ]:
x2 = list(functions.values())

In [ ]:
mydic2={}

In [ ]:
x2 = set(x2)
x2

In [ ]:
x2 = list(x2)
x2

In [ ]:
functions1=None

In [ ]:
base_dataset['fare'].std()

In [ ]:
functions.values()

In [ ]:
columns_list1=[]
if ' and ' in ques1:
    for i in ques1.split():
        if i in column

In [ ]:
querry = 'multiply the values of fare and pclass'

In [ ]:
if

In [ ]:
elif ' and ' in ques:
    for j in ques.split():
        if j in columns_list:
            column_list.append(i)
        elif j in functions:
            funtions1=j
    x=functions[functions1]

In [ ]:
column1=[]
for i in base_dataset.columns:
    for j in string.split():
        if i==j:
            column1.append(i)
print(column1)
aggregated_columns=input()
column2=[i for i in column1 if i not in aggregated_columns]
base_dataset[base_dataset[aggregated_columns]>30][column2].mean()

In [ ]:
functions_imp = functions_2

In [ ]:
if ' line plot ' in ques:
        column1=[]
        for i in base_dataset.columns:
                for j in ques.split():
                    if i==j:
                        column1.append(i)
        sns.relplot(base_dataset[column1[0]],base_dataset[column1[1]],kind="line")

# Working Dummy Code

In [ ]:
if ' correlation ' in ques:
    print(base_dataset.corr()) 
else:
    for i in ques.split():
        if i in columns_list:
            columns=i
        elif i in functions:
            functions1=i
    x=functions[functions1]
    if x == 'sqrt':
        print(np.sqrt(base_dataset[columns]))
    else:
        print(eval("base_dataset[columns]"+"."+x))

In [ ]:
column1=[]

if ' greater than ' in ques:
    for i in base_dataset.columns:
        for j in ques.split():
            if i==j:
                column1.append(i)
    print(column1)
    aggregated_columns=input()
    column2=[i for i in column1 if i not in aggregated_columns]
    for k in ques.split():
        if k in functions:
            function1=k
    x=functions[function1]
    for c in ques.split():
        if c.isdigit():
            num=c
    print(eval("base_dataset[base_dataset[aggregated_columns]>"+ num +"][column2]."+x))
    
column1=[]
if 'less than' in ques:
    for i in base_dataset.columns:
        for j in ques.split():
            if i==j:
                column1.append(i)
    print(column1)
    aggregated_columns=input()
    column2=[i for i in column1 if i not in aggregated_columns]
    for k in ques.split():
        if k in functions:
            function1=k
    x=functions[function1]
    for c in ques.split():
        if c.isdigit():
            num=c
    print(eval("base_dataset[base_dataset[aggregated_columns]<"+ num +"][column2]."+x))
    
    
column1=[]
if ' equal to ' in ques:
    for i in base_dataset.columns:
        for j in ques.split():
            if i==j:
                column1.append(i)
    print(column1)
    aggregated_columns=input()
    column2=[i for i in column1 if i not in aggregated_columns]
    for k in ques.split():
        if k in functions:
            function1=k
    x=functions[function1]
    for c in ques.split():
        if c.isdigit():
            num=c
    print(eval("base_dataset[base_dataset[aggregated_columns]="+ num +"][column2]."+x))

In [ ]:
if ' rug plot ' in ques:
    for i in ques.split():
        if i in columns_list:
            columns=i
    sns.rugplot(base_dataset[columns])

In [ ]:
if ' kde plot ' in ques:
    column1=[]
    for i in base_dataset.columns:
            for j in ques.split():
                if i==j:
                    column1.append(i)
    if len(column1)==1:
        sns.kdeplot(base_dataset[column1[0]])
    elif len(column1)==2:
        sns.kdeplot(base_dataset[column1[0]],base_dataset[column1[1]],shade=True,cbar=True)

In [ ]:
if ' joint plot ' in ques:
    column1=[]
    for i in base_dataset.columns:
            for j in ques.split():
                if i==j:
                    column1.append(i)
    if 'linear regression' in ques:
        sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='reg')
    elif 'kernel density' in ques:
        sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='kde')
    elif 'hexagon' in ques:
        sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]],kind='hex')
    else:
        sns.jointplot(base_dataset[column1[0]],base_dataset[column1[1]])

In [ ]:
if ' dist plot ' in ques:
    for i in ques.split():
        if i in columns_list:
            columns=i
    base_dataset_copy=base_dataset
    base_dataset_copy[columns].fillna(0,inplace=True)
    sns.distplot(base_dataset_copy[columns])

In [ ]:
if ' pair plot ' in ques:
    column1=[]
    for i in base_dataset.columns:
            for j in ques.split():
                if i==j:
                    column1.append(i)
    column1_copy=[]
    for i in column1:
        column1_copy.append(base_dataset[i])
    column1_copy=pd.DataFrame(column1_copy).T
    if 'kernel density' in ques:
        sns.pairplot(column1_copy,diag_kind='kde')
    elif 'linear regression' in ques:
        sns.pairplot(column1_copy,kind='reg')
    else:
        sns.pairplot(column1_copy)

In [ ]:
def func5():
    operator = 'or'
    cols2=[]
    num1=[]
    func1=[]
    for i in ques.split():
        if i in columns_list:
            columns2.append(i)
        elif i in functions.keys():
            func1.append(i)
        elif i.isdigit():
            num1.append(i)

    column_1=cols2[1]
    column_2=cols2[2]
    column_3=cols2[0]
    function_key_1=func1[1]
    function_key_2=func1[2]
    function_key_3=func1[0]
    function_1=functions[function_key_1]
    function_2=functions[function_key_2]
    function_3=functions[function_key_3]
    number1=num1[0]
    number2=num1[1]
    w=[]
    ques_comb1=[]
    for i in ques.split('and'):
        ques_comb1.append(i)
    for i in ques_comb1:
        if ' greater than ' or ' more than ' in i:
            w.append('>')
        elif ' less than ' or ' lower than ' in i:
            w.append('<')
    if operator=='and' :
        if eval(("base_dataset[column_1]."+function_1+w[0]+number1) or ("base_dataset[column_2]." +function_2+ w[1]+ number2)):
            print(eval("base_dataset[column_3]."+function_3))

In [117]:
base_dataset.to_html("simple1.html")

In [118]:
pwd

'C:\\Users\\Aritra\\Downloads'